export  * from './acidenteTransito.model';
export  * from './dadosAcidenteTransito.model';
export  * from './instituicao.model';
export  * from './localizacao.model';
export  * from './tipoVeiculo.model';
export  * from './usuario.model';
export  * from './veiculo.model';
export  * from './UsuarioPermissao.model';
export  * from './UrlFotos.model';
